services:
  db:
    image: postgres:15-alpine
    container_name: parking-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ParkingDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    container_name: parking-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
